wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nft_contract: "b59cee8ea11307d6b911bf314ef01d63071448f3"
auction_contract: "dfee94168795a48395cdb9ba078a46363c77795e"
storage_node: "localhost:8080"
storage_container: "7efD5UoKmZcejw7ek36k8wX2SznZRjLBcEkHQ91M4Ku4"
listen_address: ":5555"
ticket_api_url: "https://678b8b8a1a6b89b27a2aaf17.mockapi.io/jsonticket/tickets/ticket/"