wallet: "../../frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nyan_contract: "29a854a7741b84160c46172c8121de11486533a3"
storage_node: "localhost:8080"
storage_container: "HJQScRmAKnsKmxsGcphFxp6irE68GQBqNETG6XdrqVoF"
listen_address: ":5555"