wallet: "/home/d/frostfs-aio/wallets/wallet1.json"
password: ""
rpc_endpoint: "http://localhost:30333"
rpc_endpoint_ws: "ws://localhost:30333/ws"
nft_contract: "460e3fd16593aec0bf19346120fce9662a02de2e"
auction_contract: "ba3a8bd67146a341e97c50d9a1aaa53b62353566"
storage_node: "localhost:8080"
storage_container: "G4iewnjVFMwmQbzAmABkRetYdJ4aJauAw61tsJQ8S5jK"
listen_address: ":5555"
ticket_api_url: "https://678b8b8a1a6b89b27a2aaf17.mockapi.io/jsonticket/tickets/ticket/"